require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const DB_USER = process.env.DB_USER || 'root';
const DB_PASS = process.env.DB_PASSWORD || '';
const DB_NAME = process.env.DB_NAME || 'bentabet_db';
const BACKUP_DIR = path.join(__dirname, '..', '..', 'backups');

// Step 1: Pre-cleanup backup
console.log('Creating pre-cleanup backup...');
const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
const backupFile = path.join(BACKUP_DIR, `pre_dupe_cleanup_${ts}.sql`);
const dumpCmd = `mysqldump -u ${DB_USER} -p${DB_PASS} --single-transaction --quick --routines --triggers ${DB_NAME}`;
execSync(`${dumpCmd} > "${backupFile}"`, { shell: 'cmd.exe', timeout: 60000, stdio: 'pipe' });
const size = fs.statSync(backupFile).size;
console.log(`Backup saved: ${backupFile} (${(size / 1024 / 1024).toFixed(2)} MB)`);

// Step 2: Find duplicate indexes
console.log('\nScanning for duplicate indexes...');
const env = { MYSQL_PWD: DB_PASS };
const result = execSync(
  `mysql -u ${DB_USER} -N -e "SELECT TABLE_NAME, INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = '${DB_NAME}' AND INDEX_NAME REGEXP '_[0-9]+$' ORDER BY TABLE_NAME, INDEX_NAME;"`,
  { env, shell: 'cmd.exe', timeout: 15000, encoding: 'utf-8' }
);

const lines = result.trim().split('\n').filter(l => l.trim().length > 0);
if (lines.length === 0) {
  console.log('No duplicate indexes found. Database is clean.');
  process.exit(0);
}

// Parse the output
const indexes = lines.map(l => {
  const parts = l.trim().split('\t');
  return { table: parts[0], index: parts[1] };
});

// Group by table
const byTable = {};
for (const idx of indexes) {
  if (!byTable[idx.table]) byTable[idx.table] = [];
  byTable[idx.table].push(idx.index);
}

// Generate cleanup SQL
const sqlFile = path.join(BACKUP_DIR, `cleanup_dupe_indexes_${ts}.sql`);
let sql = `-- Cleanup duplicate indexes - ${ts}\n`;
sql += `-- Generated by cleanup_dupes.js\n`;
sql += `-- Total duplicate indexes to drop: ${indexes.length}\n\n`;
sql += `USE \`${DB_NAME}\`;\n\n`;

let total = 0;
for (const [table, idxs] of Object.entries(byTable)) {
  sql += `-- ${table}: ${idxs.length} duplicate indexes\n`;
  for (const idx of idxs) {
    sql += `ALTER TABLE \`${table}\` DROP INDEX \`${idx}\`;\n`;
    total++;
  }
  sql += '\n';
}

sql += `-- Total: ${total} indexes dropped\n`;
fs.writeFileSync(sqlFile, sql, 'utf-8');

console.log(`\nFound ${indexes.length} duplicate indexes across ${Object.keys(byTable).length} tables:`);
for (const [table, idxs] of Object.entries(byTable)) {
  console.log(`  ${table}: ${idxs.length} indexes`);
}
console.log(`\nCleanup SQL written to: ${sqlFile}`);

// Step 3: Execute cleanup (dry run unless --execute flag)
if (process.argv.includes('--execute')) {
  console.log('\nExecuting cleanup...');
  execSync(`mysql -u ${DB_USER} -p${DB_PASS} ${DB_NAME} < "${sqlFile}"`, { env, shell: 'cmd.exe', timeout: 60000, stdio: 'pipe' });
  console.log('Cleanup executed successfully.');
} else {
  console.log('\nDRY RUN — pass --execute to apply.');
  console.log(`Review: type "${sqlFile}"`);
}
